name: Publish to DockerHub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    ## docker pull arnaugarcia97/arnaugarcia.com
    ## docker rm $(docker stop $(docker ps -a -q --filter ancestor=arnaugarcia97/arnaugarcia.com --format="{{.ID}}"))
    ## docker run -d -p 3000:3000 arnaugarcia97/arnaugarcia.com
